---
title: "Diverting Our Attention To Information Practices"
description: |
  Going out into the world to understand information organization practices and cultures.
author:
  - name: Nicholas Bosco
    url: {}
date: 2022-04-16
preview: 
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
During the winter semester in the class *INF315: Information Practice in Organizations*, I was a part of a team tasked with conducting a field study about one part of the student service processes offered at the University of Toronto's iSchool. The team members were: George Zhiqi Chen, Oliver Daniel and Yahui Zhang. The specific part of student services we looked into was the Faculty of Information Master Admissions Process. This position is held by Jennifer Duggan. To understand what goes on in Jennifer's day to day activities as the Master Admissions Officer for the iSchool, we conducted several interviews asking both from the perspective of tasks and daily procedures she follows to the types of things we, as outsiders to the admissions process do not typically get to see like work culture and the unique position Jennifer has in the grand scheme of Admissions. We learned that Jennifer's job as an Admissions Officer is like a "really long river," providing the students who apply and have the potential to benefit from completing their post-grad education at the iSchool. 

What I had learned from interviewing Jennifer and presenting the information with the group we had gathered about the Master Admissions position is that diverting our attention toward a specific practice and having some proximity from the content we are trying to learn about organizations themselves are very complex. The group members and I were just fortunate enough to share the conversation with Jennifer.

