---
title: "What Do We Talk About, When We Talk About Museums?"
description: |
 Museums are places of wonder and awe. But the experiences gathered from each person is solely unique.
author:
  - name: Nicholas Bosco
    url: {}
date: 2022-04-16
preview: "Modigliani_portrait.jpeg"
output:
  distill::distill_article:
    self_contained: false
---

<!-- Image from: https://commons.wikimedia.org/wiki/File:%27Portrait_of_a_Woman%27_by_Amedeo_Modigliani,_1917-18,_Cleveland_Museum_of_Art.JPG -->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
In any society, we are bound by certain norms that dictate how we ought to behave in the presence of others. When you want to watch a movie in the theatres, you have to abide by the unspoken rule of not speaking because you and everyone else is there to enjoy the movie. When watching a sports game, people go with the sole purpose of seeing professionals what they do best and to experience the game first hand. Some roam through the isles in a grocery store to figure out what they need to purchase, but the grocery store itself is a meeting place to get food. So now the question is, *why do museums mediate the experience of visitors?* A short answer is that museums collect the memories of many but present them to a broader scope of people to satisfy their individual needs.

Museums generally take up lots of space within the cities they occupy and require special attention for the objects, performances and conversations it shelters from the elements of mother nature. Although in our minds, Museums accomplish many things for some, they can finally put an image to how we imagine "true beauty" to look like. Museums can convey power the particular country has by conquering its’ enemies prized possessions; museums can also remind us about those who lived on earth many millennia before I am here today writing this blog post. However, not only the objects or performances within the many rooms can invoke these thoughts; that is only half of the battle. The other half of the battle comes from the professionals who run the museum to ensure it operates to its prestigious glory. From the conservationists to the curators, every employee within the museum has a role to play.

Imagine the first time you were at a museum. You walk through the doors and are immediately blown away by the sheer amount of objects, from "ordinary" spoons to dinosaur bones. But you do a mini shuffle in a directed path meticulously charted out by the museum director/curator, and you just follow the person in front of you. For a moment, you pause at a painting of a person that you feel is just watching you as you move. You then feel a sudden chill and think to yourself: "Those eyes are very creepy. I think they are following me." As a member of the museum, you are now participating just like everyone else in the room, forming your own thoughts and feelings after interacting with the painting. And as you get older, you look back at that first moment thinking about the painting. This curiously/desire to learn more is the reason why you find yourself back in that exact spot having a tête-à-tête(a private conversation) with the painting yet again with the hope to get something different the next time the two of you meet.

